- name: "Create zellij dir"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ xdg_data_home }}/zellij"
    - "{{ tmp_dir }}/zellij"
    - "{{ xdg_config_home }}/zellij"
- name: "Featch zellij"
  get_url:
    dest: "{{ tmp_dir }}/zellij/{{ source_name }}"
    url: "{{ source_url }}"
    mode: "744"
  when: ansible_facts['os_family'] == "Debian"
- name: "Extract the binary"
  unarchive:
    src: "{{ tmp_dir }}/zellij/{{ source_name }}"
    remote_src: true
    dest: "{{ xdg_data_home }}/zellij"
    mode: "0755"
    creates: "{{ xdg_data_home }}/zellij/zellij"
  when: ansible_facts['os_family'] == "Debian"
- name: "Create link to binay file"
  file:
    src: "{{ xdg_data_home }}/zellij/zellij"
    dest: "{{ xdg_bin_home }}/zellij"
    state: "link"
  when: ansible_facts['os_family'] == "Debian"
- name: "Install nvim(brew)"
  homebrew:
    name: "zellij"
  when: ansible_facts['os_family'] == "Darwin"
- name: "Copy setting direcotry"
  copy:
    src: "zellij/"
    dest: "{{ xdg_config_home }}/zellij"
    mode: "0755"
